'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Modal } from './ui/dialog';

type Fact = {id:string;text:string;source:string;expires:string;approved_by:number|null};
type Pack = {id:number;client_id:number;version:number;brand_voice:string;audience_segments:string[];offers:string[];facts:Fact[];prohibited_claims:string[];compliance_notes:string};
type Report = {id:number;title:string;status:string;pack_version:number;approved_facts:Fact[];metrics:Record<string,string|number|null>;interpretation:string;recommendations:string;open_questions:string};
type Review = {pack_id:number;version:number;facts:Fact[]};
async function api(path:string,options:RequestInit={}) {const response=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json','X-Requested-With':'PaidGrowth',...options.headers}});const body=await response.json();if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail));return body;}

export function ContextWorkspace({role,clientList}:{role:string;clientList:{id:number;name:string}[]}) {
  const [packs,setPacks]=useState<Pack[]>([]);const [reports,setReports]=useState<Report[]>([]);const [facts,setFacts]=useState<Review[]>([]);const [review,setReview]=useState<Review[]>([]);const [campaigns,setCampaigns]=useState<{id:number;title:string}[]>([]);
  const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [open,setOpen]=useState(false);const [draftPack,setDraftPack]=useState<Pack|null>(null);const [selected,setSelected]=useState<Report|null>(null);
  const refresh=useCallback(async()=>{try{const [r,c]=await Promise.all([api('/context/reports'),api('/records/campaigns?limit=100')]);setReports(r);setCampaigns(c.items);if(role==='client'){setFacts(await api('/context/approved-facts'));setReview(await api('/context/fact-review'));}else setPacks(await api('/context/packs'));}catch(e){setError((e as Error).message);}},[role]);
  useEffect(()=>{void refresh();},[refresh]);
  async function action(path:string,body:unknown){setBusy(true);setError('');try{const result=await api(path,{method:'POST',body:JSON.stringify(body)});setMessage(result.review_flags?.length?`Draft created with flags: ${result.review_flags.join('; ')}`:'Saved. Approval and audit history are updated.');await refresh();return result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
  async function savePack(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{const payload={client_id:Number(f.get('client_id')),brand_voice:String(f.get('brand_voice')),audience_segments:String(f.get('audience_segments')).split('\n').filter(Boolean),offers:String(f.get('offers')).split('\n').filter(Boolean),facts:JSON.parse(String(f.get('facts'))),prohibited_claims:String(f.get('prohibited_claims')).split('\n').filter(Boolean),compliance_notes:String(f.get('compliance_notes'))};if(await action('/context/packs',payload))setOpen(false);}catch{setError('Facts must be a valid JSON array with id, text, source, and expires.');}}
  async function generate(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await action('/context/generate',{pack_id:Number(f.get('pack_id')),campaign_id:Number(f.get('campaign_id')),fact_ids:String(f.get('fact_ids')).split(',').map(s=>s.trim()).filter(Boolean),format:f.get('format')});}
  async function report(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await action('/context/reports',{pack_id:Number(f.get('pack_id')),campaign_id:Number(f.get('campaign_id')),kind:f.get('kind')});}
  return <><div className="page-heading"><div><p className="eyebrow">GROUNDED CONTEXT</p><h1>Words with evidence.</h1><p className="muted">Approved facts. Considered copy. Client-ready narratives.</p></div>{role==='account_manager'&&<button className="primary" onClick={()=>{setDraftPack(null);setOpen(true);}}>New Context Pack version</button>}</div>{error&&<p className="alert error" role="alert">{error}</p>}{message&&<p className="alert success" role="status">{message}</p>}
  {role==='client'?<><section className="panel"><h2>Facts you approved</h2><p className="muted">Only your approvals appear in this view. Expiry dates remain visible.</p>{facts.map(p=><div key={p.pack_id}><h3>Context version {p.version} · #{p.pack_id}</h3>{p.facts.map(f=><p className="comment" key={f.id}><b>{f.text}</b><span>Source: {f.source}</span><small>{f.id} · Expires {f.expires}</small></p>)}</div>)}</section><section className="panel"><h2>Fact approval requests</h2><p className="muted">These proposed facts are awaiting your decision and are separate from approved facts.</p>{review.map(p=><div key={p.pack_id}>{p.facts.map(f=><div className="comment" key={f.id}><p><b>{f.text}</b></p><p className="small muted">Source: {f.source} · Expires {f.expires} · Version {p.version}</p><button className="secondary" disabled={busy} onClick={()=>void action(`/context/packs/${p.pack_id}/facts/approve`,{fact_ids:[f.id]})}>Approve this fact</button></div>)}</div>)}</section></>:<section className="panel"><h2>Versioned Client Context Packs</h2><p className="small muted">Only Account Managers can create or edit versions. New versions reset fact approvals.</p>{packs.map(p=><article className="context-pack" key={p.id}><div className="panel-heading"><h3>{clientList.find(c=>c.id===p.client_id)?.name||`Client #${p.client_id}`} · Version {p.version}</h3><span className="badge">Pack #{p.id}</span></div><p><b>Brand voice:</b> {p.brand_voice}</p><p><b>Audience:</b> {p.audience_segments.join('; ')}</p><p><b>Offers:</b> {p.offers.join('; ')||'None recorded'}</p><p><b>Prohibited:</b> {p.prohibited_claims.join('; ')||'None recorded'}</p><p><b>Compliance:</b> {p.compliance_notes||'None recorded'}</p>{p.facts.map(f=><p className="comment" key={f.id}><b>{f.id}: {f.text}</b><span>{f.source} · Expires {f.expires}</span><small>{f.approved_by?'Client approved':'Awaiting client approval'}</small></p>)}{role==='account_manager'&&<button className="secondary" onClick={()=>{setDraftPack(p);setOpen(true);}}>Create next version</button>}</article>)}{!packs.length&&<p className="empty">An Account Manager can create the first pack.</p>}</section>}
  {['account_manager','creative'].includes(role)&&<section className="panel"><h2>Template-based copy drafting</h2><p className="muted">Generate a brief and cited copy from approved facts. Drafts enter Creative Review as “Draft — Generated”. No publishing occurs.</p><form onSubmit={generate} className="record-form"><label>Context Pack<select name="pack_id" required><option value="">Select…</option>{packs.map(p=><option key={p.id} value={p.id}>#{p.id} · Client #{p.client_id} · Version {p.version}</option>)}</select></label><label>Campaign<select name="campaign_id" required><option value="">Select…</option>{campaigns.map(c=><option key={c.id} value={c.id}>#{c.id} · {c.title}</option>)}</select></label><label>Approved fact IDs<input name="fact_ids" required placeholder="service_area, offer_terms"/></label><label>Format<select name="format">{['Headline','Primary Text','CTA','TV Script','Outdoor Script'].map(f=><option key={f}>{f}</option>)}</select></label><div className="form-actions"><button className="primary" disabled={busy}>Generate draft</button></div></form></section>}
  {['account_manager','campaign_specialist'].includes(role)&&<section className="panel"><h2>Prepare a client narrative</h2><p className="muted">Numbers are drawn from one campaign reporting period and saved as a timestamped snapshot.</p><form className="record-form" onSubmit={report}><label>Context Pack<select name="pack_id" required><option value="">Select…</option>{packs.map(p=><option key={p.id} value={p.id}>Pack #{p.id} · Version {p.version}</option>)}</select></label><label>Campaign<select name="campaign_id" required><option value="">Select…</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Report type<select name="kind"><option>Monthly Report</option><option>Client Review Summary</option></select></label><div className="form-actions"><button className="primary" disabled={busy}>Prepare report</button></div></form></section>}
  <section className="panel"><h2>Client narratives</h2>{reports.map(r=><div className="schedule-row" key={r.id}><div><b>{r.title}</b><small>Context version {r.pack_version}</small></div><span className="badge">{r.status}</span><button className="text-button" onClick={()=>setSelected(r)}>Review</button></div>)}{!reports.length&&<p className="empty">No reports available for review yet.</p>}</section>
  <Modal open={open} onOpenChange={setOpen} title="Client Context Pack" description="A new version preserves history and requires fresh client fact approval."><form className="record-form" onSubmit={savePack}><label>Client<select name="client_id" required defaultValue={draftPack?.client_id||''}><option value="">Select…</option>{clientList.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Brand voice<textarea name="brand_voice" required defaultValue={draftPack?.brand_voice||''}/></label><label>Audience segments — one per line<textarea name="audience_segments" required defaultValue={draftPack?.audience_segments.join('\n')||''}/></label><label>Offers — one per line<textarea name="offers" defaultValue={draftPack?.offers.join('\n')||''}/></label><label>Facts — JSON array<textarea name="facts" required defaultValue={JSON.stringify(draftPack?draftPack.facts.map(({id,text,source,expires})=>({id,text,source,expires})):[],null,2)} placeholder={'[{"id":"service_area","text":"Approved factual statement","source":"Document reference","expires":"2027-01-01"}]'}/></label><label>Prohibited claims — one per line<textarea name="prohibited_claims" defaultValue={draftPack?.prohibited_claims.join('\n')||''}/></label><label>Compliance notes<textarea name="compliance_notes" defaultValue={draftPack?.compliance_notes||''}/></label>{error&&<p role="alert" className="alert error">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy}>Save new version</button></div></form></Modal>
  <Modal open={selected!==null} onOpenChange={v=>{if(!v)setSelected(null);}} title={selected?.title||'Report'} description="Results → Interpretation → Recommendations → Open questions.">{selected&&<><span className="badge">{selected.status}</span><h3 className="section-label">Results (facts)</h3><dl className="detail-grid">{Object.entries(selected.metrics).map(([k,v])=><div key={k}><dt>{k.replace(/_/g,' ')}</dt><dd>{v??'Unavailable'}</dd></div>)}</dl>{selected.approved_facts.map(f=><p className="comment" key={f.id}><b>{f.text} [fact:{f.id}]</b><small>{f.source} · Expires {f.expires}</small></p>)}<h3 className="section-label">Interpretation</h3><p>{selected.interpretation}</p><h3>Recommendations</h3><p>{selected.recommendations}</p><h3>Open questions</h3><p>{selected.open_questions}</p><p className="small muted">This snapshot preserves the stored metrics at preparation time. Later campaign edits require a new report.</p><div className="form-actions"><a className="secondary" href={`/api/context/reports/${selected.id}/pdf`}>Export PDF</a>{((role==='account_manager'&&selected.status==='Draft')||(role==='client'&&selected.status==='Account Approved'))&&<><button className="secondary" disabled={busy} onClick={async()=>{const updated=await action(`/context/reports/${selected.id}/approve`,{decision:'Request Changes'});if(updated)setSelected(role==='client'?null:updated);}}>Request changes</button><button className="primary" disabled={busy} onClick={async()=>{const updated=await action(`/context/reports/${selected.id}/approve`,{decision:'Approve'});if(updated)setSelected(updated);}}>Approve report</button></>}</div>{error&&<p className="alert error" role="alert">{error}</p>}</>}</Modal></>;
}
