'use client';

import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { ArrowDownToLine, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, FileImage, LayoutDashboard, LogOut, Plus, Search, Users, X } from 'lucide-react';
import { Modal } from '@/components/ui/dialog';
import { ContextWorkspace } from '@/components/context-workspace';
import { modules, type Row } from '@/lib/modules';

type User = {id:number; name:string; email:string; role:string; agency:string; demo:boolean};
type Event = {id:number; record_id:number|null; action:string; detail:{body?:string;author?:string;note?:string;from?:string;to?:string};created_at:string};
type Group = {currency:string; timezone:string; attribution:string; source:string; start_date:string; end_date:string; budget:number;spend:number;leads:number;ctr:number|null;cpl:number|null;roas:number|null};
type Dashboard = {counts:Record<string,number>; groups:Group[];campaigns:Row[];demo:boolean};
const icons = {dashboard:LayoutDashboard,clients:Users,orders:ClipboardList,employees:Users,tasks:Check,creatives:FileImage,campaigns:BarChart3,calendar:CalendarDays,activity:Bell,context:FileImage};
const labels:Record<string,string> = {dashboard:'Overview',clients:'Clients',orders:'Orders',employees:'Team',tasks:'Tasks',creatives:'Creative review',campaigns:'Campaigns',calendar:'Calendar',activity:'Activity',context:'Context & reports'};
const names = (key:string) => key.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const number = (n:number|null|undefined) => n == null ? '—' : new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(n);
const money = (n:number,currency:string) => new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:0}).format(n);

async function api(path:string, options:RequestInit = {}) {
  const response = await fetch(`/api${path}`, {...options, headers:{'Content-Type':'application/json','X-Requested-With':'PaidGrowth',...options.headers},credentials:'include'});
  if (!response.ok) {
    let message = `Request failed (${response.status})`;
    try { const error = await response.json(); message = typeof error.detail === 'string' ? error.detail : JSON.stringify(error.detail); } catch { /* keep status */ }
    throw new Error(message);
  }
  return response.status === 204 ? null : response.json();
}

export default function Home() {
  const [user,setUser] = useState<User|null>(null);
  const [checking,setChecking] = useState(true);
  const [tab,setTab] = useState('dashboard');
  const [data,setData] = useState<Dashboard|null>(null);
  const [rows,setRows] = useState<Row[]>([]);
  const [clients,setClients] = useState<Row[]>([]);
  const [team,setTeam] = useState<Row[]>([]);
  const [events,setEvents] = useState<Event[]>([]);
  const [notifications,setNotifications] = useState<Event[]>([]);
  const [query,setQuery] = useState('');
  const [offset,setOffset] = useState(0);
  const [total,setTotal] = useState(0);
  const [loading,setLoading] = useState(false);
  const [error,setError] = useState('');
  const [success,setSuccess] = useState('');
  const [editing,setEditing] = useState<Row|null|undefined>(undefined);
  const [detail,setDetail] = useState<Row|null>(null);
  const [detailEvents,setDetailEvents] = useState<Event[]>([]);
  const [saving,setSaving] = useState(false);
  const [groupIndex,setGroupIndex] = useState(0);
  const [reportClient,setReportClient] = useState('');
  const [reportChannel,setReportChannel] = useState('');
  const config = modules[tab];
  const exportQuery = new URLSearchParams();
  if (reportClient) exportQuery.set('client_id', reportClient);
  if (reportChannel) exportQuery.set('channel', reportChannel);
  const canWrite = !!user && !!config?.roles.includes(user.role);

  useEffect(()=>{ api('/auth/me').then(setUser).catch(()=>{}).finally(()=>setChecking(false)); },[]);
  const refresh = useCallback(async()=>{
    if (!user) return;
    setLoading(true); setError('');
    try {
      const dashboard = await api('/dashboard'); setData(dashboard);
      const [clientData,notificationData] = await Promise.all([api('/records/clients?limit=100'),api('/notifications')]);
      setClients(clientData.items); setNotifications(notificationData);
      if (user.role !== 'client') setTeam(await api('/team'));
      if (modules[tab]) { const result = await api(`/records/${tab}?q=${encodeURIComponent(query)}&offset=${offset}&limit=20`); setRows(result.items);setTotal(result.total); }
      if (tab === 'activity') setEvents(await api('/activity'));
    } catch(e) {setError((e as Error).message);} finally {setLoading(false);}
  },[user,tab,query,offset]);
  useEffect(()=>{let active=true;const timer=setTimeout(()=>{if(active)void refresh();},200);return()=>{active=false;clearTimeout(timer);};},[refresh]);

  async function signIn(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();setSaving(true);setError('');
    const form=new FormData(event.currentTarget);
    try {await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});setUser(await api('/auth/me'));}catch(e){setError((e as Error).message);}finally{setSaving(false);}
  }
  async function save(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();setSaving(true);setError('');
    const form=new FormData(event.currentTarget);const payload:Record<string,unknown>={};
    for(const field of config.fields){const value=String(form.get(field.key)??'');payload[field.key]=['number','client','team'].includes(field.type||'')?(value===''?null:Number(value)):(field.type==='date'&&value===''?null:value);}
    if(tab==='creatives')payload.version=editing?.version||1;
    try {await api(`/records/${tab}${editing?.id?`/${editing.id}`:''}`,{method:editing?.id?'PUT':'POST',body:JSON.stringify(payload)});setEditing(undefined);setSuccess('Saved. Your workspace is up to date.');await refresh();}catch(e){setError((e as Error).message);}finally{setSaving(false);}
  }
  async function showDetail(row:Row){setDetail(row);try{setDetailEvents(await api(`/activity?record_id=${row.id}`));}catch(e){setError((e as Error).message);}}
  async function decision(status:string){if(!detail)return;setSaving(true);try{const result=await api(`/creatives/${detail.id}/decision`,{method:'POST',body:JSON.stringify({status})});setDetail(result);setSuccess('Your review decision has been recorded.');await refresh();setDetailEvents(await api(`/activity?record_id=${detail.id}`));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  async function comment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail)return;const element=event.currentTarget;const form=new FormData(element);setSaving(true);try{await api('/comments',{method:'POST',body:JSON.stringify({record_id:detail.id,body:form.get('body'),mention_ids:form.get('mention')?[Number(form.get('mention'))]:[]})});element.reset();setDetailEvents(await api(`/activity?record_id=${detail.id}`));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  async function importFile(file:File|undefined){if(!file)return;if(file.size>1_000_000||!file.name.toLowerCase().endsWith('.csv')){setError('Choose a CSV file smaller than 1 MB.');return;}setSaving(true);try{const result=await api('/reports/import',{method:'POST',headers:{'Content-Type':'text/csv'},body:await file.text()});setSuccess(`Imported ${result.imported} campaigns.`);await refresh();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  function navigate(next:string){setTab(next);setOffset(0);setQuery('');setSuccess('');setError('');setRows([]);}
  function display(row:Row,key:string){const value=row[key];if(value==null||value==='')return '—';if(key==='client_id')return clients.find(c=>c.id===value)?.name||`Client #${value}`;if(key==='owner_id')return team.find(t=>t.id===value)?.name||`User #${value}`;if(key==='budget'||key==='spend')return money(Number(value),String(row.currency||'USD'));return String(value);}

  if(checking)return <main className="center"><div className="loader"/><p>Opening your workspace…</p></main>;
  if(!user)return <main className="login"><section className="login-story"><div className="brand"><span className="brand-mark">pg.</span><span>Paid Growth,<br/>Measured</span></div><div><p className="eyebrow">THE AGENCY WORKSPACE</p><h1>Good work.<br/>Clear evidence.<br/><em>Shared growth.</em></h1><p className="intro">Bring your clients, creative work, and campaign decisions into one considered workspace.</p></div><p className="login-foot">Less scattered work. More room to move forward.</p></section><section className="login-form"><p className="eyebrow">WELCOME BACK</p><h2>Your next chapter<br/>starts here.</h2><p className="muted">Sign in with your agency account.</p><form onSubmit={signIn}><label>Email address<input name="email" type="email" required autoComplete="username" placeholder="you@agency.com"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p role="alert" className="alert error">{error}</p>}<button className="primary" disabled={saving}>{saving?'Signing in…':'Open workspace'}<ArrowUpRight size={18}/></button></form><p className="muted small">Local demo: use an example.test account and the private password configured during setup.</p></section></main>;

  const group=data?.groups[Math.min(groupIndex,Math.max(0,(data?.groups.length||1)-1))];
  const available=Object.keys(labels).filter(key=>user.role!=='client'||['dashboard','clients','creatives','campaigns','calendar','activity','context'].includes(key)).filter(key=>key!=='employees'||['administrator','account_manager'].includes(user.role));
  return <div className="workspace"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('dashboard');}}><span className="brand-mark">pg.</span><span>Paid Growth,<br/>Measured</span></a><p className="nav-caption">WORKSPACE</p><nav aria-label="Main navigation">{available.map(key=>{const Icon=icons[key as keyof typeof icons];return <button key={key} className={tab===key?'nav-item active':'nav-item'} onClick={()=>navigate(key)}><Icon size={18}/><span>{labels[key]}</span>{key==='creatives'&&data?.counts.creatives?<small>{data.counts.creatives}</small>:null}</button>;})}</nav><div className="sidebar-note"><span className="tiny-dot"/>A little clarity goes a long way.<p>Plan with intent.<br/>Measure with care.</p></div><button className="user-card" onClick={async()=>{try{await api('/auth/logout',{method:'POST'});setUser(null);setData(null);}catch(e){setError((e as Error).message);}}}><span className="avatar">{user.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span><b>{user.name}</b><small>{names(user.role)}</small></span><LogOut size={16}/></button></aside>
  <main className="main"><header className="topbar"><span>{user.agency}</span><div><span className="connection"><i/>Local workspace</span><button className="icon-button" aria-label={`Activity, ${notifications.length} notifications`} onClick={()=>navigate('activity')}><Bell size={19}/>{notifications.length>0&&<span className="notification-dot"/>}</button></div></header>
  {user.demo&&<div className="demo-banner">DEMONSTRATION WORKSPACE <span>All seeded records and performance figures are synthetic.</span></div>}
  <div className="page-content">{error&&<div className="alert error" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{success&&<div className="alert success" role="status">{success}<button className="icon-button" aria-label="Dismiss message" onClick={()=>setSuccess('')}><X size={16}/></button></div>}
  <div className="page-heading"><div><p className="eyebrow">{tab==='dashboard'?'YOUR WORK, IN FOCUS':'AGENCY OPERATIONS'}</p><h1>{tab==='dashboard'?'A clearer view of growth.':config?.title||labels[tab]}</h1><p className="muted">{tab==='dashboard'?'Keep the work moving. Let the evidence guide your next step.':config?.subtitle||'See the next deadline and the decisions that move work forward.'}</p></div>{canWrite&&<button className="primary" onClick={()=>setEditing(null)}><Plus size={18}/>New {tab==='creatives'?'creative':tab==='employees'?'team record':tab.slice(0,-1)}</button>}</div>
  {loading&&<p className="loading" role="status">Updating workspace…</p>}
  {tab==='context'&&<ContextWorkspace role={user.role} clientList={clients.map(c=>({id:c.id,name:String(c.name)}))}/>}
  {tab==='dashboard'&&<><section className="stat-grid">{[['Active workspace','clients','Clients connected'],['Campaigns','campaigns','Reporting records'],['Delivery','orders','Advertising orders'],['Creative','creatives','Versioned deliverables']].filter(([,key])=>data?.counts[key]!=null).map(([label,key,caption])=><article className="stat-card" key={key}><span>{label}</span><strong>{data?.counts[key]||0}</strong><small>{caption}</small><ArrowUpRight size={18}/></article>)}</section>
  <section className="dashboard-grid"><article className="panel performance"><div className="panel-heading"><div><p className="eyebrow">EVIDENCE OVER ASSUMPTIONS</p><h2>Performance, in context.</h2></div><BarChart3 size={21}/></div>{group?<><label className="group-select">Comparable reporting group<select value={Math.min(groupIndex,(data?.groups.length||1)-1)} onChange={e=>setGroupIndex(Number(e.target.value))}>{data?.groups.map((g,i)=><option key={i} value={i}>{g.currency} · {g.source} · {g.start_date} – {g.end_date} · {g.attribution}</option>)}</select></label><div className="spend-line"><div><span className="muted">Recorded spend</span><strong>{money(group.spend,group.currency)}</strong></div><div><span className="muted">Planned budget</span><b>{money(group.budget,group.currency)}</b></div></div><div className="budget-track" role="img" aria-label={`Spend ${number(group.budget?group.spend/group.budget*100:0)} percent of planned budget`}><span style={{width:`${Math.min(100,group.budget?group.spend/group.budget*100:0)}%`}}/></div><div className="metric-row"><div><small>Leads</small><b>{number(group.leads)}</b></div><div><small>Cost per lead</small><b>{group.cpl==null?'—':money(group.cpl,group.currency)}</b></div><div><small>Click-through rate</small><b>{group.ctr==null?'—':`${number(group.ctr)}%`}</b></div><div><small>ROAS</small><b>{group.roas==null?'—':`${number(group.roas)}×`}</b></div></div><p className="small muted">{group.start_date} – {group.end_date} · {group.timezone}<br/>{group.attribution} · {group.source}. Missing denominators show —.</p></>:<div className="empty">Your first campaign will bring this view to life.<button className="secondary" onClick={()=>navigate('campaigns')}>Explore campaigns</button></div>}</article>
  <article className="panel next-step"><p className="eyebrow">A LITTLE MOMENTUM</p><h2>From brief<br/>to better decisions.</h2><p>Keep the next step small, clear, and owned.</p><ol><li>Connect a client</li><li>Confirm the deliverables</li><li>Review the creative</li><li>Record the results</li></ol><button onClick={()=>navigate('orders')} className="text-button">Open your orders <ArrowUpRight size={18}/></button></article></section>
  <section className="panel"><div className="panel-heading"><h2>Campaign schedule</h2><button className="text-button" onClick={()=>navigate('calendar')}>View calendar <ArrowUpRight size={16}/></button></div>{data?.campaigns.length?<div className="schedule">{data.campaigns.slice(0,5).map(c=><div className="schedule-row" key={c.id}><span className="schedule-date">{String(c.start_date).slice(5)}</span><div><b>{c.title}</b><small>{c.channel} · {c.start_date} → {c.end_date}</small></div><span className="badge">{c.status}</span></div>)}</div>:<p className="muted">No campaigns scheduled yet.</p>}</section></>}
  {config&&<section className="panel"><div className="table-toolbar"><label className="search"><Search size={17}/><input aria-label={`Search ${tab}`} placeholder={`Search ${labels[tab].toLowerCase()}…`} value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><span className="muted small">{total} records</span>{tab==='campaigns'&&<div className="report-tools"><select aria-label="Export client filter" value={reportClient} onChange={e=>setReportClient(e.target.value)}><option value="">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Export channel filter" value={reportChannel} onChange={e=>setReportChannel(e.target.value)}><option value="">All channels</option>{modules.campaigns.fields.find(f=>f.key==='channel')?.options?.map(c=><option key={c}>{c}</option>)}</select><a className="secondary" href={`/api/reports/campaigns.csv?${exportQuery.toString()}`}><ArrowDownToLine size={16}/>Export CSV</a>{canWrite&&<label className="secondary">{saving?'Importing…':'Import CSV'}<input type="file" accept=".csv,text/csv" disabled={saving} className="file-input" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label>}</div>}</div>
  <div className="table-scroll"><table><thead><tr><th>ID</th>{config.columns.map(key=><th key={key}>{names(key)}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="muted">#{row.id}</td>{config.columns.map(key=><td key={key}>{key==='status'?<span className="badge">{display(row,key)}</span>:display(row,key)}</td>)}<td><button className="text-button" onClick={()=>void showDetail(row)}>View</button>{canWrite&&<button className="text-button" onClick={()=>setEditing(row)}>Edit</button>}</td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<div className="empty"><h3>{query?'No matching records.':'A fresh page for your work.'}</h3><p>{query?'Try a different search.':'Add your first record to get started.'}</p></div>}<div className="pagination"><button className="secondary" disabled={offset===0||loading} onClick={()=>setOffset(Math.max(0,offset-20))}><ChevronLeft size={16}/>Previous</button><span className="small muted">{total?`${offset+1}–${Math.min(offset+20,total)} of ${total}`:'0 records'}</span><button className="secondary" disabled={offset+20>=total||loading} onClick={()=>setOffset(offset+20)}>Next<ChevronRight size={16}/></button></div></section>}
  {tab==='calendar'&&<section className="panel"><h2>Campaign calendar</h2><p className="muted">Scheduled periods are shown in each campaign’s reporting timezone.</p><div className="calendar-grid">{data?.campaigns.map(c=><article key={c.id}><p className="eyebrow">{c.channel}</p><h3>{c.title}</h3><p>{c.start_date} → {c.end_date}</p><small>{c.timezone}</small><span className="badge">{c.status}</span></article>)}</div>{!data?.campaigns.length&&<p className="empty">No scheduled campaigns yet.</p>}</section>}
  {tab==='activity'&&<section className="panel"><div className="panel-heading"><h2>Workspace activity</h2><span className="badge">{notifications.length} notifications</span></div><p className="small muted">Recent decisions and mentions appear here. External messages are not sent.</p>{events.map(event=><article className="event" key={event.id}><span className="event-dot"/><div><b>{event.action==='comment'?`${event.detail.author}: ${event.detail.body}`:names(event.action.replace(/\./g,' '))}</b><p>{event.detail.note|| (event.detail.to?`${event.detail.from} → ${event.detail.to}`:'') }</p><small className="muted">{new Date(event.created_at).toLocaleString()} {event.record_id?`· Record #${event.record_id}`:''}</small></div></article>)}{!events.length&&<p className="empty">Your next saved action will appear here.</p>}</section>}
  <footer>Paid Growth, Measured <span>Thoughtful operations. Accountable decisions.</span></footer></div></main>
  <Modal open={editing!==undefined} onOpenChange={open=>{if(!open)setEditing(undefined);}} title={`${editing?'Edit':'New'} ${labels[tab]?.toLowerCase()}`} description="Save a clear record. Required fields are marked with an asterisk."><form onSubmit={save} className="record-form">{config?.fields.map(field=><label key={field.key}>{field.label}{field.required?' *':''}{field.type==='textarea'?<textarea name={field.key} defaultValue={String(editing?.[field.key]??field.default??'')} maxLength={field.key==='copy'?8000:3000}/>:field.options||['client','team'].includes(field.type||'')?<select name={field.key} required={field.required} defaultValue={String(editing?.[field.key]??field.default??field.options?.[0]??'')}><option value="">Select…</option>{field.options?.map(option=><option key={option}>{option}</option>)}{(field.type==='client'?clients:field.type==='team'?team:[]).map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>:<input name={field.key} type={field.type||'text'} required={field.required} defaultValue={String(editing?.[field.key]??field.default??'')} min={field.type==='number'?0:undefined} step={field.type==='number'?'any':undefined} maxLength={field.type==='url'?2048:254}/>}</label>)}{error&&<p className="alert error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setEditing(undefined)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save record'}</button></div></form></Modal>
  <Modal open={detail!==null} onOpenChange={open=>{if(!open)setDetail(null);}} title={String(detail?.title||detail?.name||'Record')} description={`Record #${detail?.id} · Changes are recorded in activity history.`}>{detail&&<><dl className="detail-grid">{Object.entries(detail).filter(([key])=>!['id','created_at','updated_at'].includes(key)).map(([key,value])=><div key={key}><dt>{names(key)}</dt><dd>{key==='asset_url'&&value?<a href={String(value)} target="_blank" rel="noopener noreferrer">Open asset reference <ArrowUpRight size={14}/></a>:display(detail,key)}</dd></div>)}</dl>{tab==='creatives'&&detail.status==='Submitted'&&['client','administrator','account_manager'].includes(user.role)&&<div className="form-actions"><button className="secondary" disabled={saving} onClick={()=>void decision('Changes Requested')}>Request changes</button><button className="primary" disabled={saving} onClick={()=>void decision('Approved')}>Approve creative</button></div>}{tab==='creatives'&&canWrite&&<button className="secondary" onClick={()=>{setEditing({...detail,id:0,previous_id:detail.id,status:'Draft'});setDetail(null);}}>Prepare a new version</button>}<h3 className="section-label">Conversation & history</h3>{detailEvents.map(event=><p className="comment" key={event.id}><b>{event.detail.author||names(event.action.replace(/\./g,' '))}</b><span>{event.detail.body||event.detail.note||event.detail.to||'Saved to the activity ledger.'}</span><small>{new Date(event.created_at).toLocaleString()}</small></p>)}<form onSubmit={comment}><label>Add a comment<textarea name="body" required maxLength={2000} placeholder="Share a clear next step…"/></label>{user.role!=='client'&&<label>Mention a teammate<select name="mention"><option value="">No mention</option>{team.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label>}<button className="primary" disabled={saving}>Add comment</button></form>{error&&<p className="alert error" role="alert">{error}</p>}</>}</Modal></div>;
}
