export type Row = {id: number; [key: string]: string | number | null};
export type Field = {key: string; label: string; type?: string; required?: boolean; options?: string[]; default?: string | number};
export type Module = {title: string; subtitle: string; fields: Field[]; columns: string[]; roles: string[]};
const title: Field = {key:'title',label:'Title',required:true};
const client: Field = {key:'client_id',label:'Client',type:'client',required:true};
const owner: Field = {key:'owner_id',label:'Assigned to',type:'team'};
const channel: Field = {key:'channel',label:'Channel',options:['Paid Social','Search','Display','Television','Outdoor'],required:true};
const budget: Field = {key:'budget',label:'Planned budget',type:'number',required:true,default:0};
const currency: Field = {key:'currency',label:'Currency',default:'USD',required:true};
const managers = ['administrator','account_manager'];
export const modules: Record<string, Module> = {
  clients:{title:'Client relationships',subtitle:'Know the people behind every project.',columns:['name','contact','email','follow_up'],roles:managers,fields:[{key:'name',label:'Organization',required:true},{key:'contact',label:'Contact name'},{key:'email',label:'Email',type:'email'},{key:'communication',label:'Preferred communication',default:'Email'},owner,{key:'opportunity',label:'Opportunity'},{key:'follow_up',label:'Next follow-up',type:'date'},{key:'notes',label:'Account notes',type:'textarea'}]},
  employees:{title:'Your team',subtitle:'Clear responsibilities. Shared momentum.',columns:['name','role','responsibilities'],roles:managers,fields:[{key:'name',label:'Name',required:true},{key:'role',label:'Role',required:true},{key:'user_id',label:'Linked account',type:'team'},{key:'responsibilities',label:'Responsibilities',type:'textarea'}]},
  orders:{title:'Advertising orders',subtitle:'From a clear brief to a completed delivery.',columns:['title','client_id','channel','budget','deadline','status'],roles:managers,fields:[title,client,channel,budget,currency,{key:'deadline',label:'Deadline',type:'date',required:true},owner,{key:'deliverables',label:'Deliverables',type:'textarea'},{key:'notes',label:'Internal notes',type:'textarea'},{key:'status',label:'Status',options:['Draft','Confirmed','In Progress','Awaiting Approval','Completed','Cancelled'],default:'Draft'}]},
  tasks:{title:'Work in motion',subtitle:'Give every deliverable an owner and a deadline.',columns:['title','owner_id','deadline','status'],roles:[...managers,'campaign_specialist','creative'],fields:[title,client,{key:'order_id',label:'Order ID',type:'number'},{key:'campaign_id',label:'Campaign ID',type:'number'},owner,{key:'deadline',label:'Deadline',type:'date',required:true},{key:'status',label:'Status',options:['To Do','In Progress','Done'],default:'To Do'}]},
  creatives:{title:'Creative review',subtitle:'Build a strong idea. Keep every decision visible.',columns:['title','client_id','version','status'],roles:[...managers,'creative'],fields:[title,client,{key:'order_id',label:'Order ID',type:'number'},{key:'brief',label:'Creative brief',type:'textarea'},{key:'copy',label:'Advertising copy',type:'textarea'},{key:'asset_url',label:'HTTPS asset reference',type:'url'},{key:'previous_id',label:'Previous version ID',type:'number'},{key:'status',label:'Status',options:['Draft','Draft — Generated','Submitted'],default:'Draft'}]},
  campaigns:{title:'Campaign performance',subtitle:'Connect activity to evidence, one reporting period at a time.',columns:['title','channel','budget','spend','leads','start_date','end_date','status'],roles:[...managers,'campaign_specialist'],fields:[title,client,channel,{key:'objective',label:'Objective',default:'Lead generation'},owner,{key:'start_date',label:'Period start',type:'date',required:true},{key:'end_date',label:'Period end',type:'date',required:true},currency,{key:'timezone',label:'Timezone',default:'Asia/Karachi',required:true},{key:'attribution',label:'Attribution',default:'7-day click',required:true},{key:'source',label:'Data source',default:'Manual',required:true},budget,...['spend','impressions','clicks','leads','conversions','revenue'].map(key=>({key,label:key[0].toUpperCase()+key.slice(1),type:'number',default:0})),{key:'status',label:'Status',options:['Planned','Active','Paused','Completed'],default:'Planned'}]},
};
